### ISSUE TITLE
Update the library to reflect the most recent API changes

### ISSUE THREAD

**Issue by hajekj** [Microsoft/ApplicationInsights-PHP#15]
Since I couldn't find a documentation for the AI API, I figured that the following has to be changed:

- When passing on the `status` in `trackRequest` or `endRequest` method on `ApplicationInsights\Telemetry_Client` it is required to be a **string** not an *integer*.
- Similar goes for `begingRequest` method in `ApplicationInsights\Telemetry_Client` where the request ID is required to be a **string** but it is set as *integer* [instead](https://github.com/Microsoft/ApplicationInsights-PHP/blob/9523fc0c1a008e8fd5c665b838109f6af16eecbd/ApplicationInsights/Telemetry_Client.php#L175).

The AI API sends a response of HTTP 400 and the message looks like "106: ..."

There is probably more to this, but I haven't discovered it during my usage.

**Comment by AlexBulankou** [comment]
@hajekj can you please include full request to and response from AI dc endpoint? (you can capture it using Fiddler or similar tool). Thanks!

**Comment by hajekj** [comment]
@AlexBulankou: I got the GuzzleHttp object which contains entire request details, I hope it will do.
[ai_guzzle_log.txt](https://github.com/Microsoft/ApplicationInsights-PHP/files/253030/ai_guzzle_log.txt)

**Comment by hajekj** [comment]
Additionally, the [AI for Node.js](https://github.com/Microsoft/ApplicationInsights-node.js/) already does this:

- [Uses GUIDs instead of random integers for IDs](https://github.com/Microsoft/ApplicationInsights-node.js/blob/7b545ba8e955c96eb104009f7d020cd3eb49765f/AutoCollection/RequestDataHelper.ts#L60)
- [Treats response codes as strings](https://github.com/Microsoft/ApplicationInsights-node.js/blob/7b545ba8e955c96eb104009f7d020cd3eb49765f/AutoCollection/RequestDataHelper.ts#L60)

However it appears that Node.js does this from the very beginning (based on file history), however there must have been some backend change, because it used to work with the integers without any issues.

**Comment by AlexBulankou** [comment]
I tried sending the payload from the file you attached to endpoint and the first error I'm getting is this:
HTTP/1.1 400 106: Field 'id' on type 'RequestData' is of incorrect type. Expected: string, Actual: 802738029
As you discovered there could be others. Our new data collection endpoint is doing stricter validation, which caused the issue. Since PHP SDK is not officially supported by AI team, I would recommend that you open Issues and either fix them yourself or wait till other users of this SDK fix it.
I agree that it would be very helpful to have a full set of rules available. @lukekim @youngbupark - do you have a reference like this?

**Comment by youngbupark** [comment]
PHP sdk is not affected by strict-mode now.  @hajekj,  Seems like you're using really old sdk. Please try the latest one.

{"ai.location.ip":"141.101.97.60","ai.session.id":"0hk9mf3dst7cnkfof137e0isc0","ai.user.id":"26ED030A-EF3B-4E86-85D1-C585A4AC58AA",**"ai.internal.sdkVersion":"php:0.1.0"**}

**Comment by youngbupark** [comment]
(I was confused due to the unchanged sdkVersion in PHP sdk. Need to change the version string to 0.3.2 as well)

Currently, PHP SDK is not affected by strict-mode validation since this is for the future versions and we didn't get the similar issues from other SDK/customers. As we see the endpoint data scheme, it has been treated as string as before. As per dotnet sdk, it always treats it as string.
